version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recraftify-service
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - /app/node_modules
      